Add multi-stage docker build
Changes the dockerfile process to use a two-stage build process.

* Defines the existing ruby:3.1.3-alpine3.17 base image as base.
* Uses the base image to define a builder image which installs build
dependencies, gems and javascript dependencies, and compiles the
application's assets.
* Uses the base image to define the final image which copies across only
the files it needs from the builder image (ie the bundle and application
source code).

This results in a greatly reduced final docker image size.

diff --git a/docker/Dockerfile b/docker/Dockerfile
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -1,10 +1,12 @@
-FROM ruby:3.1.3-alpine3.17
-LABEL Organisation="Ministry of Justice"
-LABEL Service="Claim for Crown Court Defence"
-LABEL Contact="crowncourtdefence@digital.justice.gov.uk"
+FROM ruby:3.1.3-alpine3.17 AS base
+
+FROM base AS builder
 
 # fail early and print all commands
 RUN set -ex
+
+ENV APP_HOME /usr/src/app
+WORKDIR $APP_HOME
 
 # build dependencies:
 # -virtual: create virtual package for later deletion
@@ -15,40 +17,14 @@ RUN set -ex
 # - git for installing gems referred to use as git:// uri
 # - yarn for js dependency management
 #
-# runtime dependencies:
-# - file: for paperclip file type spoofing check
-# - nodejs: for ExecJS and asset compilation
-# - runit for process management (because we have multiple services)
-# - libreoffice: for pdf conversion
-# - ttf-freefont: needed for libreoffice
-# - redis: for backend key-value store
-# - postgresql-client - only needed for database dump
-#
-RUN apk --no-cache add --virtual build-dependencies \
-                    build-base \
-                    libxml2-dev \
-                    libxslt-dev \
-                    postgresql-dev \
-                    git \
-                    yarn \
-                    gmp=6.2.1-r2 \
-&& apk --no-cache add \
-                  file \
-                  nodejs \
-                  linux-headers \
-                  runit \
-                  ttf-freefont \
-                  libreoffice \
-                  redis \
-                  postgresql-client
-
-# add non-root user and group with alpine first available uid, 1000
-RUN addgroup -g 1000 -S appgroup \
-&& adduser -u 1000 -S appuser -G appgroup
-
-# create app directory in conventional, existing dir /usr/src
-RUN mkdir -p /usr/src/app && mkdir -p /usr/src/app/tmp
-WORKDIR /usr/src/app
+RUN apk --no-cache add \
+                   build-base \
+                   libxml2-dev \
+                   libxslt-dev \
+                   postgresql-dev \
+                   git \
+                   yarn \
+                   gmp=6.2.1-r2
 
 ######################
 # DEPENDENCIES START #
@@ -56,7 +32,7 @@ WORKDIR /usr/src/app
 # Env vars needed for dependency install and asset precompilation?? maybe not
 ENV RAILS_ENV production
 
-COPY Gemfile* ./
+COPY Gemfile Gemfile.lock $APP_HOME/
 
 # only install production dependencies,
 # build nokogiri using libxml2-dev, libxslt-dev
@@ -67,13 +43,10 @@ RUN gem install bundler -v $(cat Gemfile.lock | tail -1 | tr -d " ") \
 && bundle config build.nokogiri --use-system-libraries \
 && bundle install
 
-COPY package.json yarn.lock ./
+COPY package.json yarn.lock $APP_HOME/
 RUN yarn install --frozen-lockfile --production --silent
 
-####################
-# DEPENDENCIES END #
-####################
-COPY . .
+COPY . $APP_HOME/
 
 # precompile assets, silently (as verbose)
 RUN SECRET_KEY_BASE=a-real-secret-key-is-not-needed-here \
@@ -81,10 +54,52 @@ RAILS_ENV=production \
 bundle exec rails assets:precompile 2> /dev/null
 
 # tidy up installation
-RUN apk --update-cache upgrade && apk del build-dependencies
+RUN apk --update-cache upgrade
 
-# non-root/appuser should own only what they need to
-RUN chown -R appuser:appgroup log tmp db
+####################
+# DEPENDENCIES END #
+####################
+
+FROM base
+LABEL Organisation="Ministry of Justice"
+LABEL Service="Claim for Crown Court Defence"
+LABEL Contact="crowncourtdefence@digital.justice.gov.uk"
+
+# fail early and print all commands
+RUN set -ex
+
+ENV RAILS_ENV production
+ENV APP_HOME /usr/src/app
+WORKDIR $APP_HOME
+
+# runtime dependencies:
+# - file: for paperclip file type spoofing check
+# - nodejs: for ExecJS and asset compilation
+# - runit for process management (because we have multiple services)
+# - libreoffice: for pdf conversion
+# - ttf-freefont: needed for libreoffice
+# - redis: for backend key-value store
+# - postgresql-client - only needed for database dump
+#
+RUN apk --no-cache add \
+                   file \
+                   nodejs \
+                   linux-headers \
+                   runit \
+                   ttf-freefont \
+                   libreoffice \
+                   redis \
+                   postgresql-client
+
+# add non-root user and group with alpine first available uid, 1000
+RUN addgroup -g 1000 -S appgroup \
+&& adduser -u 1000 -S appuser -G appgroup
+
+COPY --from=builder /usr/local/bundle/ /usr/local/bundle/
+COPY --from=builder --chown=appuser:appgroup $APP_HOME $APP_HOME
+
+# tidy up installation
+RUN apk --update-cache upgrade
 
 # expect ping environment variables
 ARG VERSION_NUMBER
